# Generated by Django 5.2.6 on 2025-09-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_promoimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Mission', max_length=200)),
                ('description', models.TextField(default='Every day with every connection, Petpalooza passionate associates help bring pet parents closer to their pets so they can live more fulfilled life')),
                ('image', models.ImageField(upload_to='backgrounds/')),
            ],
        ),
    ]
