# Generated by Django 5.2.6 on 2025-09-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutcontent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ANYTHING for PETS®', max_length=200)),
                ('content', models.TextField(default='\nWe love pets, and we believe loving pets makes us better people. That’s one of the many reasons we do Anything for Pets – because they will do anything for us. Anything for Pets is our commitment to pet parents, it’s how we do business and who we are as pet lovers. As the leader in pet care, we make our decisions based on how we can bring pet parents closer to their pets. From dressing in matching costumes, to finding the perfect treats and toys, we innovate solutions and unique, must-have products to create more ways for pets to be a part of our everyday lives. Our trusted and skilled associates share the same passion for pets as the pet parents we serve, helping pet parents choose from our offering of the largest variety of pet products and services in one convenient place – in your neighborhood or the palm of your hand. With more than 1,660 locations in North America, we pride ourselves on our unrivaled variety of pet food, treats, toys, and apparel, as well as our services including training, grooming, boarding and more.\n')),
            ],
        ),
    ]
