# Generated by Django 5.2.6 on 2025-09-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_aboutcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='cards/')),
            ],
        ),
    ]
