# Generated by Django 5.2.6 on 2025-09-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetSmartHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='highlights/')),
            ],
        ),
    ]
