# Generated by Django 5.2.6 on 2025-09-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_browsetopic_quicklink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='browsetopic',
            name='order',
        ),
        migrations.RemoveField(
            model_name='quicklink',
            name='order',
        ),
        migrations.AlterField(
            model_name='browsetopic',
            name='icon',
            field=models.ImageField(upload_to='icons/browse_topics/'),
        ),
        migrations.AlterField(
            model_name='browsetopic',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quicklink',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quicklink',
            name='icon',
            field=models.ImageField(upload_to='icons/quick_links/'),
        ),
        migrations.AlterField(
            model_name='quicklink',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
