# Generated by Django 5.2.6 on 2025-09-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_remove_browsetopic_order_remove_quicklink_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsetopic',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order for sorting display'),
        ),
        migrations.AddField(
            model_name='quicklink',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order for sorting display'),
        ),
    ]
