# Generated by Django 5.2.6 on 2025-09-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0013_bannerimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='center_images/')),
            ],
        ),
    ]
