# Generated by Django 5.2.6 on 2025-09-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0014_centerimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='pet_services/')),
                ('button_text', models.CharField(default='Learn More', max_length=50)),
            ],
        ),
    ]
