# Generated by Django 5.2.6 on 2025-09-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0016_footercontent_socialicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='dog_products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('reviews_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='promo_banners/')),
            ],
        ),
    ]
