# Generated by Django 5.2.6 on 2025-09-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0018_catbanner_catproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catproduct',
            name='image',
            field=models.ImageField(upload_to='cat_products/'),
        ),
    ]
