# Generated by Django 5.2.6 on 2025-09-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0019_alter_catproduct_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='banners/')),
                ('extra_image1', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('extra_image2', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('offer_text', models.CharField(blank=True, max_length=100, null=True)),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('button_link', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
