# Generated by Django 5.2.6 on 2025-09-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0020_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Stress-Free Summer', max_length=200)),
                ('subtitle', models.CharField(default='Keep your pup calm along all season', max_length=255)),
                ('image', models.ImageField(upload_to='dog_banner/')),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
