# Generated by Django 5.2.6 on 2025-09-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0022_productdetail_productimagedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Dog Food Background', max_length=100)),
                ('image', models.ImageField(upload_to='backgrounds/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
