# Generated by Django 5.2.6 on 2025-09-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0027_footericon_paymentmethod_productmain'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogCardGreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('left_image', models.ImageField(upload_to='dogcardgreen/')),
                ('right_image', models.ImageField(upload_to='dogcardgreen/')),
            ],
        ),
    ]
