# Generated by Django 5.2.6 on 2025-09-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0028_dogcardgreen'),
    ]

    operations = [
        migrations.CreateModel(
            name='LargeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Product Image', max_length=200)),
                ('main_image', models.ImageField(upload_to='products/main/')),
                ('thumb1', models.ImageField(blank=True, null=True, upload_to='products/thumbs/')),
                ('thumb2', models.ImageField(blank=True, null=True, upload_to='products/thumbs/')),
                ('thumb3', models.ImageField(blank=True, null=True, upload_to='products/thumbs/')),
                ('thumb4', models.ImageField(blank=True, null=True, upload_to='products/thumbs/')),
                ('thumb5', models.ImageField(blank=True, null=True, upload_to='products/thumbs/')),
            ],
        ),
    ]
