# Generated by Django 5.2.6 on 2025-09-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0029_largeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='dog_images/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_logo', models.BooleanField(default=False)),
            ],
        ),
    ]
