# Generated by Django 5.2.6 on 2025-09-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0030_dogpet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogpet',
            name='image',
        ),
        migrations.RemoveField(
            model_name='dogpet',
            name='is_logo',
        ),
        migrations.AddField(
            model_name='dogpet',
            name='left_bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
        migrations.AddField(
            model_name='dogpet',
            name='right_bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
    ]
