# Generated by Django 5.2.6 on 2025-09-29 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0031_remove_dogpet_image_remove_dogpet_is_logo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dogpet',
            old_name='left_bg_image',
            new_name='background_image',
        ),
        migrations.RemoveField(
            model_name='dogpet',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='dogpet',
            name='right_bg_image',
        ),
    ]
