# Generated by Django 5.2.6 on 2025-09-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0032_rename_left_bg_image_dogpet_background_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogPetServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='petservices/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
