# Generated by Django 5.2.6 on 2025-09-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0034_smallbanner_smallproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Instant and complete vet care', max_length=255)),
                ('description', models.TextField(default='Wherever you are At only 299 , get end-to-end support from our vets')),
                ('button_text', models.CharField(default='Consult Now', max_length=50)),
                ('image', models.ImageField(upload_to='vetdoctor_images/')),
            ],
        ),
    ]
