# Generated by Django 5.2.6 on 2025-09-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0035_vetdoctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='consult_icons/')),
            ],
        ),
    ]
