# Generated by Django 5.2.6 on 2025-09-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0036_consult'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogWomen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dogwomen/')),
            ],
        ),
    ]
